### ISSUE TITLE
Document how to set this up with Portainer

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#144]

**Comment by rohankapoorcom** [comment]
Hah - I just went through setting all of this up with Portainer yesterday :) Would be happy to proof read any of the setup steps.

**Comment by danecreekphotography** [comment]
@rohankapoorcom That would be amazing, can you share any details? I've never used Portainer. Were you doing this through Portainer in Home Assistant running on something other than a Raspberry Pi?

**Comment by rohankapoorcom** [comment]
Sure - now that we've gotten this working (in the other) thread, I'm able to share some details.

I run portainer on a dedicated VM on my VMware vSphere cluster. The final working portainer `docker-compose.yaml` that I used is as follows:

``
version: "2"
services:
  trigger:
    volumes:
       # note that blueiris-aiinput refers to a volume that already exists in portainer that contains my aiinput files from blueiris (cifs mounted)
      - blueiris-aiinput:/aiinput
      # note that deepstack-ai-blueiris-trigger-config refers to a volume that already exists in portainer that contains the /config for the trigger (also cifs mounted)
      - deepstack-ai-blueiris-trigger-config:/config

    environment:
      - TZ=America/Los_Angeles
      - DEEPSTACK_URI=http://deepstack-ai:5000/
      - VERBOSE=true

    image: danecreekphotography/node-deepstackai-trigger:issue151
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

# note the driver:local was needed here otherwise portainer wouldn't create a volume that was stack scoped.
volumes:
  localstorage:
    driver: local
```

**Comment by Viksie** [comment]
My progress has been painful, with the situation being as follows: 

I couldn't "connect" to the "node-deepstackai-trigger" container running the "latest" image:

```
root@docker:/var/lib/docker/volumes/ai-trigger/_data# docker exec -it 477d77803b17 /bin/bash
Error response from daemon: Container 477d77803b175295768945e7230002585ee1375b16019482eaa6f682a606b6d9 is restarting, wait until the container is running
```

Neither could I "connect" with the latest "dev" image:

```
root@docker:/var/lib/docker/volumes/ai-trigger/_data# docker exec -it d2a0a7e3fd0e /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
```

I currently have no clue how to interact with the "node-deepstackai-trigger" container, except for viewing it's logs:

```
root@docker:/var/lib/docker/volumes/ai-trigger/_data# docker logs d2a0a7e3fd0e
2020-06-11T08:53:28+10:00 [Main] Starting up version 1.7.0
2020-06-11T08:53:28+10:00 [Main] Timezone offset is -600
2020-06-11T08:53:28+10:00 [Main] Current time is Thu Jun 11 2020 08:53:28 GMT+1000 (Australian Eastern Standard Time)
2020-06-11T08:53:28+10:00 [Trigger Manager] Unable to read the configuration file: ENOENT: no such file or directory, open '/run/secrets/triggers'.
2020-06-11T08:53:28+10:00 [Trigger manager] Loaded configuration from /config/triggers.json
2020-06-11T08:53:28+10:00 [Trigger manager] Loaded configuration for Person detector
2020-06-11T08:53:28+10:00 [Trigger manager] Loaded configuration for Car detector
2020-06-11T08:53:28+10:00 [Trigger manager] Loaded configuration for Cat detector
2020-06-11T08:53:28+10:00 [Trigger manager] Loaded configuration for Dog detector
2020-06-11T08:53:28+10:00 [MQTT Manager] Unable to read the configuration file: ENOENT: no such file or directory, open '/run/secrets/mqtt'.
2020-06-11T08:53:28+10:00 [MQTT manager] Loaded configuration from /config/mqtt.json
2020-06-11T08:53:28+10:00 [Main] [MQTT Manager] Unable to connect: getaddrinfo ENOTFOUND mqtt

```
Do note that my configs' location is related to my stack config as defined in portainer.io and which I then manually placed there:

```
---
version: "2"
services:
  ai-trigger:
    image: danecreekphotography/node-deepstackai-trigger:dev
    container_name: ai-trigger
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Pretoria
      - DEEPSTACK_URI=http://deepstack:5000/
      - VERBOSE=true
    volumes:
      - /aiinput:/aiinput
      # Host:VM
      - ai-trigger:/config
#    secrets:
#      - triggers
#      - mqtt
#      - telegram
    restart: unless-stopped
    depends_on:
      - deepstack

  deepstack:
    image: deepquestai/deepstack:latest
    container_name: deepstack
    environment:
      - PUID=1000
      - PGID=1000
      - VISION-DETECTION=True
    volumes:
      - deepstack:/datastore 
    ports:
      - 5000:5000
    restart: unless-stopped
```

The contents of /var/lib/docker/volumes/ai-trigger/_data of which i manually placed the files there :

```
root@docker:/var/lib/docker/volumes/ai-trigger/_data# ls -la
total 20
drwxr-xr-x 2 root root 4096 Jun 11 01:06 .
drwxr-xr-x 3 root root 4096 Jun 10 23:42 ..
-rw-r--r-- 1 root root  264 Jun 10 23:55 mqtt.json
-rw-r--r-- 1 root root  223 Jun 10 23:55 telegram.json
-rw-r--r-- 1 root root 2878 Jun 10 23:54 triggers.json
```

The contents of /var/lib/docker/volumes/deepstack/_data :

```
root@dc-01:/var/lib/docker/volumes/deepstack/_data# ls -al
total 16
drwxr-xr-x 2 root root 4096 Jun 10 23:42 .
drwxr-xr-x 3 root root 4096 Jun 10 23:42 ..
-rw-r--r-- 1 root root 5120 Jun 10 23:42 faceembedding.db
```

With portainer only supporting version 2 of docker compose configs, "secrets" is an "unsupported config option". Neither do I currently understand their relevance.

Yet ...

Copying an .jfif image of a dog into the /aiinput folder of the docker host creates no log entry.
Copying an .jpg image of a dog into the /aiinput folder of the docker host creates no log entry.

and I'm a bit stuck on how to continue ...
