### ISSUE TITLE
Add Home Assistant integration information to the wiki

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#149]
Explain how to create an MQTT binary sensor to respond to the motion messages.

```yaml
platform: mqtt
device_class: motion
name: "Front door motion"
state_topic: aimotion/triggers/FrontDoor
payload_on: "on"
payload_off: "off"
value_template: "{{value_json.state}}"
```
