### ISSUE TITLE
Document how to set this up with Portainer

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#184]
See https://github.com/danecreekphotography/node-deepstackai-trigger/issues/144 for ideas.

**Comment by Viksie** [comment]
- Install Docker
- Install Portainer

`sudo docker volume create portainer
sudo docker run -d -p 9000:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer `

Connect to portainer via browser:

`http://<host IP>:9000`

- Login 
- Click on "local"
- Click on "Stacks" in newly presented left side bar
- Click on "+ Add stack" button in right side bar >  Give the stack a name: ie. ai-trigger

- Past into "Web Editor" section:

`---
version: "2"
services:
  ai-trigger:
    image: danecreekphotography/node-deepstackai-trigger:latest
    container_name: ai-trigger
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New York
      - DEEPSTACK_URI=http://deepstack:5000/
      - VERBOSE=true
    volumes:
      - /aiinput:/aiinput
      # Host:VM
      - ai-trigger:/config
    ports:
      - 4242:4242
    restart: unless-stopped
    depends_on:
      - deepstack

  deepstack:
    image: deepquestai/deepstack:latest
    container_name: deepstack
    environment:
      - PUID=1000
      - PGID=1000
      - VISION-DETECTION=True
    volumes:
      - deepstack:/datastore 
    ports:
      - 5000:5000
    restart: unless-stopped`

- Click on "Deploy the stack"

*** Do NOT navigate away from the browser window UNTIL the deployment had completed ***

On the docker host, navigate to the **/var/lib/docker/volumes/ai-trigger/_data** folder.

Edit & adjust:

- settings.json
- triggers.json
- telegram.json
- mqtt.json

-------------------------------------------------------------------------------------------------------------

Acquiring a new image:

Connect to portainer via browser: 

`http://<host IP>:9000`

- Login 
- Click on "local"
- Click on "Containers" in newly presented left side bar
- Select container "ai-trigger" > Stop > Remove
- Click on "Images" in left side bar
- Select image with tag "danecreekphotography/node-deepstackai-trigger:latest" > Remove
- Click on "Stacks" in left side bar
- **Click on** stack "ai-trigger" > **Click on** "Editor" tab > **Click on** "Update the stack"

*** Do NOT navigate away from the browser window UNTIL the deployment had completed ***

*** All setttings will be retained ***

**Comment by splatura** [comment]
FYI I've taken a stab at this in Portainer 1.24.0.  Since there's support only for V2 docker-compose files, sections such as `secrets:` are not supported.  Personally I think there's value in delaying this documentation until Portainer 2.0 is released upon which time V3 docker-compose format will be supported.

**Comment by pi642s** [comment]
thank you so much for this guide.

i used proxmox.   

i have one container with homeassistant with mqtt broker.  i already have a VM with blueiris.  i enabled aiinput folder to be shared with a username and password. 

i created another container with ubuntu. set up ssh. 

i used this guide here  to set up cifs share from windows VM to a linux container: 
_https://steamforge.net/wiki/index.php/How_to_mount_a_Network_Share_in_a_Linux_Container_under_Proxmox_

i then set up docker, portainer using this guide: 
_https://www.juanmtech.com/set-up-hassio-in-docker-and-in-an-ubuntu-server/_

```
apt update
apt upgrade

apt-get install \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

apt-key fingerprint 0EBFCD88

add-apt-repository \
 "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
 $(lsb_release -cs) \
 stable"

apt-get install docker-ce docker-ce-cli containerd.io

docker run hello-world

systemctl enable docker


docker volume create portainer_data

docker run -d -p 9000:9000 \
--name portainer \
--restart always \
-v /var/run/docker.sock:/var/run/docker.sock \
-v portainer_data:/data portainer/portainer
```

then as above, add a new stack in portainer and paste 

```
version: "2"
services:
  ai-trigger:
    image: danecreekphotography/node-deepstackai-trigger:latest
    container_name: ai-trigger
    ports:
      - 4242:4242
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/winshare:/aiinput 
# Host:VM
      - ai-trigger:/config
    restart: unless-stopped
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    container_name: deepstack-ai
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VISION-DETECTION=True
    volumes:
      - localstorage:/datastore
    ports:
      - 5000:5000

```
make sure to de-select “enable access control”

use SFTP
On the docker host, navigate to the /var/lib/docker/volumes/ai-trigger/_data folder
upload settings.json and triggers.json

go to portainer/ai-trigger container and review logs to make sure everything runs correctly.
