### ISSUE TITLE
MQTT topic messages not dispatching

### ISSUE THREAD

**Issue by jasonmadigan** [danecreekphotography/node-deepstackai-trigger#233]
**Describe the bug**
I have things mostly working, triggers are setup and are firing webRequests successfully to BlueIrist to record things on detection, but for some reason I'm not seeing any mqtt messages (other than the status online/offline) being fired for hits.

I've allegedly enabled verbose logging, but logging for the trigger service in docker-compse generally is very light, which makes me question if that's enabled OK. Compose file attached later.

**Log entries**
```
c:\deepstackai-trigger>docker-compose up
Recreating deepstackai-trigger_deepstack-ai_1 ... done                                                                                                                Recreating deepstackai-trigger_trigger_1      ... done                                                                                                                Attaching to deepstackai-trigger_deepstack-ai_1, deepstackai-trigger_trigger_1
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
trigger_1       | 2020-06-15T16:18:36+01:00 [Main] Starting up version 2.0.0
trigger_1       | 2020-06-15T16:18:36+01:00 [Main] Timezone offset is -60
trigger_1       | 2020-06-15T16:18:36+01:00 [Main] Current time is Mon Jun 15 2020 16:18:36 GMT+0100 (Irish Standard Time)
trigger_1       | 2020-06-15T16:18:36+01:00 [MQTT manager] Loaded configuration from /run/secrets/mqtt
trigger_1       | 2020-06-15T16:18:36+01:00 [MQTT Manager] Connected to MQTT server mqtt://192.168.1.230:1883
trigger_1       | 2020-06-15T16:18:36+01:00 [Trigger manager] Loaded configuration from /run/secrets/triggers
trigger_1       | 2020-06-15T16:18:36+01:00 [Trigger manager] Loaded configuration for GateSD
trigger_1       | 2020-06-15T16:18:36+01:00 [Telegram Manager] Unable to read the Telegram configuration file: ENOENT: no such file or directory, open '/run/secrets/telegram'.
trigger_1       | 2020-06-15T16:18:36+01:00 [Telegram Manager] Unable to read the Telegram configuration file: ENOENT: no such file or directory, open '/config/telegram.json'.
trigger_1       | 2020-06-15T16:18:36+01:00 [Telegram Manager] Unable to find an Telegram configuration file. If Telegram was disabled in the Docker configuration then this warning can be safely ignored. Otherwise it means something is wrong with how the container is configured. Verify the telegram secret points to a file called telegram.json or that the /config mount point contains a file called telegram.json.
trigger_1       | 2020-06-15T16:18:36+01:00 [Trigger GateSD] Listening for new images in /aiinput/GateSD*.jpg
trigger_1       | 2020-06-15T16:18:36+01:00 [Main] ****************************************
trigger_1       | 2020-06-15T16:18:36+01:00 [Main] Up and running!
trigger_1       | 2020-06-15T16:18:39+01:00 [Trigger GateSD] /aiinput/GateSD.20200614_002211654.jpg: Skipping as it was created before the service started.
trigger_1       | 2020-06-15T16:15:22+01:00 [Trigger GateSD] /aiinput/GateSD.20200615_161520569.jpg: Analyzing
```

**Installation details**
 - Docker for Windows (10)

`docker-compose.yml`:

```
version: "3.8"
services:
  trigger:
    volumes:
      # Change ./path_to_local_ai_images_folder to point to the folder that
      # will have the images to analyze
      - ../aiinput:/aiinput

    environment:
      # Change this to match the timezone the images are produced in,
      # Typically this will be the timezone of the machine running
      # the Docker container. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=Europe/Dublin
      # Modify this to change the default port used for the service that returns
      # annotated images. If you change this you also have to set the same value
      # in the ports: section below.
      - PORT=4242
      # Uncomment this line to enable the internal web server and
      # generation of annotated images
      # - ENABLE_ANNOTATIONS=true
      # This is pre-configured for service-to-service connectivity in
      # Docker. Don't change this unless there is a need to talk to an
      # external DeepStack server somewhere and you know what you are doing.
      - DEEPSTACK_URI=http://deepstack-ai:5000/
      - VERBOSE=true

    ports:
      - 4242:4242

    secrets:
      - triggers
      # To enable MQTT uncomment the following line and add the server
      # connection settings to mqtt.json
      - mqtt
      # To enable Telegram uncomment the following line and add the bot
      # token to telegram.json
      # - telegram

    # ------------------------------------------------------------------------
    # Don't change anything below this line unless you know what you are doing
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore

volumes:
  localstorage:

secrets:
  triggers:
    # This should point to the location of the triggers.json configuration file
    file: ./triggers.json
  mqtt:
    # This should point to the location of the mqtt.json configuration file
    file: ./mqtt.json
  telegram:
    # This should point to the location of the telegram.json configuration file
    file: ./telegram.json
```

`triggers.json`

```
{
  "$schema": "https://raw.githubusercontent.com/danecreekphotography/node-deepstackai-trigger/master/src/schemas/triggerConfiguration.schema.json",
  "triggers": [
    {
      "name": "GateSD",
      "watchPattern": "/aiinput/GateSD*.jpg",
      "enabled": true,
      "threshold": {
        "minimum": 0,
        "maximum": 100
      },
      "handlers": {
        "webRequest": {
          "triggerUris": ["http://192.168.1.231:8181/admin?trigger&camera=GateHD&user=***&pw=***"]
        },
        "mqtt": {
          "topic": "aimotion/triggers/gatesd"
        }
      },
      "watchObjects": ["person", "bicycle", "motorcycle", "car", "truck", "bus", "cat", "dog", "bird", "horse", "cow"]
    }
  ]
}
```
