### ISSUE TITLE
Support Nx Witness-style systems

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#260]
**Is your feature request related to a problem? Please describe.**
Nx Witness doesn't support writing a snapshot out when motion is detected. What it can do is:

1. Call an URL to say "hey motion happened!"
2. Return a snapshot when a specific URL is requested

**Describe the solution you'd like**

1. Use the existing express server to expose a route for `/motion/triggerName`
2. When that route is hit, call an URL specified on the trigger to retrieve an image

**Additional context**

Originally I thought this would require an entire Nx Witness module but it can be plenty generic. Only question is where to put the image: local storage or aiinput?

**Comment by danecreekphotography** [comment]
This is mostly working. A few cleanup things to do:

1. Make `watchObjects` optional, and enforce one of `watchObjects` or `snapshotUri` instead.
2. Make sure it works with annotations enabled. There's a chance annotations would try to overwrite the original image, which might actually be ok.

**Comment by danecreekphotography** [comment]
The file does download successfully but deepstack complains that it isn't a valid image.

**Comment by danecreekphotography** [comment]
Downloads work fine but as expected it breaks annotations. Requires doing some work I've always meant to do to allow multiple local folders for storage. Hopefully that will fix it.

**Comment by danecreekphotography** [comment]
Current issues/todo:

1. Change the LocalStorageManager setup and purge to loop over Locations instead of copy/paste code.
2. Set up express to route `/` requests to `/annotations` for backwards compatibility purposes.
3. Figure out why annotation text doesn't work. Whyyyyyyy.

**Comment by danecreekphotography** [comment]
Finally solved item 3. Good grief what a pain in the butt pureimage is as a library. Item 2 is done as well, both `/` and `/annotations` serve up the annotated images.

**Comment by Viksie** [comment]
Would you mind elaborating a little bit more on how you fixed it ?

**Comment by danecreekphotography** [comment]
You can see the pull request once I open it and it'll show you all the different changes made. I'll add some comments on the PR as well to explain some of what's going on.

Fundamentally responding to the request and downloading the image is the same as what you put together in your proof of concept. It just caused a lot of ripple effect changes elsewhere.

**Comment by danecreekphotography** [comment]
https://github.com/danecreekphotography/node-deepstackai-trigger/pull/270/files is the draft pull request. The two most relevant parts are activateWebTrigger() and downloadWebImage().

**Comment by Viksie** [comment]
... uhmmm, I'm a bit lost as I don't know GitHub that well. 

Would I just grab the latest docker image by specifying :dev and construct the settings.json file within /var/lib/docker/volumes/ai-trigger/_data ?

**Comment by danecreekphotography** [comment]
None of this is available for testing yet, I'll let you know when it is and how to get it.

Until then just point to `latest`, make a settings.json, and put it in the same folder you have triggers.json in. See https://raw.githubusercontent.com/danecreekphotography/node-deepstackai-trigger/main/sampleConfiguration/settings.json for what it should look like. You probably just need the `deepstackUri` and `verbose` properties.

**Comment by Viksie** [comment]
Yes Master. Thank you Master !

**Comment by Viksie** [comment]
With MQTT, Telegram and PushOver's settings consolidated into **settings.json** is the trigger settings still left in **triggers.json** ?

**Comment by danecreekphotography** [comment]
Yes, all the triggers stay in `triggers.json`.

**Comment by Viksie** [comment]
On dropping Cat_20200523-074700.jpg into /aiinput

```
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to call DeepStack at http://deepstack-ai:5000/: Error: getaddrinfo ENOTFOUND deepstack-ai
    at /home/node/app/bundle.js:721:24164
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

```

**Comment by danecreekphotography** [comment]
You need to change `deepstackUri` in the settings file to whatever you used to have the `DEEPSTACK_URI` environment variable set to for your Docker configuration.

**Comment by Viksie** [comment]
Stopped DeepStack & node-DeepStackAI-Trigger Docker containers. Deleted docker containers. Deleted docker images.

Created settings.json in /var/lib/docker/volumes/ai-trigger/_data which reflects "deepstackUri": "http://deepstack-ai:5000/",

Pulling the latest DeepStack and node-DeepStackAI-Trigger docker images via the portainer stack config 

```
  ai-trigger:
    image: danecreekphotography/node-deepstackai-trigger:dev
    container_name: ai-trigger
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - DEEPSTACK_URI=http://deepstack:5000/
      - VERBOSE=true
    volumes:
      - /aiinput:/aiinput
      # Host:VM
      - ai-trigger:/config
#    secrets:
#      - triggers
#      - mqtt
#      - telegram
    ports:
      - 4999:4999
    restart: unless-stopped
    depends_on:
      - deepstack

  deepstack:
    image: deepquestai/deepstack:latest
    container_name: deepstack
    environment:
      - PUID=1000
      - PGID=1000
      - VISION-DETECTION=True
    volumes:
      - deepstack:/datastore 
    ports:
      - 5000:5000
    restart: unless-stopped

```
and got the issue upon dropping the first images into the /aiinput folder.
