### ISSUE TITLE
Portainer Stack update issue with new settings.json implementation

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#273]
Calls from docker container Node-DeepstackAI-Trigger to Deepstack worked perfect once setup via portainer's stack setup (docker compose v2) until now:

Steps executed:

Stopped DeepStack & node-DeepStackAI-Trigger docker containers. Deleted docker containers. Deleted docker images.

Created settings.json in /var/lib/docker/volumes/ai-trigger/_data 

```
{
  // Leave this line alone. It enables Intellisense when editing this file in Visual Studio Code.
  "$schema": "https://raw.githubusercontent.com/danecreekphotography/node-deepstackai-trigger/main/src/schemas/settings.schema.json",

  // This is the default uri for Deepstack when deploying using the docker-compose.yaml file
  // provided in this sampleConfiguration folder. If you have another deployment of Deepstack
  // running elsewhere change this setting to point to the correction location.
  "deepstackUri": "http://deepstack-ai:5000/",

  // Enables verbose logging. Useful when setting up the system to ensure
  // everything is running correctly.
  "verbose": true,

  // Provides the configuration details for your MQTT server. To enable
  // mqtt set the uri, username (if required), password (if required),
  // and set enabled to true.
  "mqtt": {
    "uri": "mqtt://mqtt:1883",
    //"username": "user",
    //"password": "pass",
    "enabled": false
  },

  // Provides the configuration details for Telegram bot messages.
  // Set the botToken and enabled to true to use Telegram.
  "telegram": {
    "botToken": "AE0000",
    "enabled": false
  },

  // Provides the configuration details for Pushover notifications.
  // Set the apiKey, userKey, and enabled to true to use Pushover.
  "pushover": {
    "apiKey": "api key here",
    "userKey": "user key here",
    "enabled": false
  }
}

```

Click on the "Update the stack" button in portainer's Stacks section (docker compose) to pull the latest DeepStack and node-DeepStackAI-Trigger images.

Stack config (compose v2)

```
---
version: "2"
services:
  ai-trigger:
    image: danecreekphotography/node-deepstackai-trigger:dev
    container_name: ai-trigger
    environment:
      - PUID=1000
      - PGID=1000
      - DEEPSTACK_URI=http://deepstack:5000/
      - VERBOSE=true
    volumes:
      - /aiinput:/aiinput
      # Host:VM
      - ai-trigger:/config
#    secrets:
#      - triggers
#      - mqtt
#      - telegram
    ports:
      - 4999:4999
    restart: unless-stopped
    depends_on:
      - deepstack

  deepstack:
    image: deepquestai/deepstack:latest
    container_name: deepstack
    environment:
      - PUID=1000
      - PGID=1000
      - VISION-DETECTION=True
    volumes:
      - deepstack:/datastore 
    ports:
      - 5000:5000
    restart: unless-stopped

```

Containers start without issues, yet generate the inter container comms issue upon dropping the first images into the /aiinput folder.

```
` [Main] Starting up version 3.0.0
 [Settings] Unable to read the configuration file: ENOENT: no such file or directory, open '/run/secrets/settings'.
 [Settings] Loaded settings from /config/settings.json
 [MQTT] MQTT is disabled via settings.
 [Local storage] Creating local storage folder /node-deepstackai-trigger/www.
 [Local storage] Enabling background purge every 60 minutes for files older than 30 minutes.
 [Local storage] Running purge
 [Triggers] Unable to read the configuration file: ENOENT: no such file or directory, open '/run/secrets/triggers'.
 [Triggers] Loaded configuration from /config/triggers.json
 [Triggers] Loaded configuration for Driveway
 [Triggers] Loaded configuration for Sidegate
 [Triggers] Loaded configuration for Dog Cam
 [Triggers] Loaded configuration for Cat Cam
 [Telegram] Telegram is disabled via settings.
 [Pushover] Pushover is disabled via settings.
 [Trigger Driveway] Listening for new images in /aiinput/Driveway*.jpg
 [Trigger Sidegate] Listening for new images in /aiinput/Sidegate*.jpg
 [Trigger Dog Cam] Listening for new images in /aiinput/Dog*.jpg
 [Trigger Cat Cam] Listening for new images in /aiinput/Cat*.jpg
 [Main] ****************************************
 [Main] Up and running!
 [Local storage] Purge complete
 [Trigger Cat Cam] /aiinput/Cat_20200523-074700.jpg: Analyzing
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to call DeepStack at http://deepstack-ai:5000/: Error: getaddrinfo ENOTFOUND deepstack-ai
    at /home/node/app/bundle.js:721:24164
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 [Trigger Cat Cam] /aiinput/Cat_20200523-075000.jpg: Analyzing
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to call DeepStack at http://deepstack-ai:5000/: Error: getaddrinfo ENOTFOUND deepstack-ai
    at /home/node/app/bundle.js:721:24164
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
 [Trigger Cat Cam] /aiinput/Cat_20200523-075100.jpg: Analyzing
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to call DeepStack at http://deepstack-ai:5000/: Error: getaddrinfo ENOTFOUND deepstack-ai
    at /home/node/app/bundle.js:721:24164
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

```
