### ISSUE TITLE
Correctly Write Mount Point for Source Images

### ISSUE THREAD

**Issue by BooneBeast** [danecreekphotography/node-deepstackai-trigger#286]
**What trouble are you having?**

I am having problems correctly entering the local path to the aiinput folder in the yml where the images are stored to be analyzed.  Is there a template format that can be shared to ensure the path is inputted correctly?  For example, if my aiinput folder was located on the C: drive and in the BlueIris folder, what is the correct way to write the path to this location?  

Similarly, what is the correct way to determine the watch pattern is written correctly?  If the images to be processed are mounted in the aiinput folder, within the BlueIris folder in the C drive folder, how is that supposed to look like in the triggers.json file?

**Have you tried with the sample files?**

- [Yes/No] Yes

**Installation details**

 - OS: [e.g. Mac, Windows 10] Windows 10
 - Docker setup [e.g. sample docker-compose.yaml, Portainer, UnRAID, etc] Docker-compose.yml

**Comment by danecreekphotography** [comment]
Please post the contents of your docker-compose.yaml file and your triggers.json file so I can assist. Thanks!

**Comment by BooneBeast** [comment]
yaml file:

```
version: "3.8"
services:
  trigger:
    volumes:
      # Change ./path_to_local_ai_images_folder to point to the folder that
      # will have the images to analyze
      - ./C:/BlueIris/aiinput

    environment:
      # Change this to match the timezone the images are produced in,
      # Typically this will be the timezone of the machine running
      # the Docker container. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=America/Indiana/Indianapolis

    ports:
      # This port is used by the local web server when annotated images are enabled.
      # If you change the port used by the local web server in the settings.json file
      # this also has to change to match.
      - 4242:4242

    # ------------------------------------------------------------------------
    # Don't change anything below this line unless you know what you are doing
    secrets:
      - triggers
      - settings
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

volumes:
  localstorage:

secrets:
  settings:
    # This should point to the location of the settings.json configuration file
    file: ./settings.json
  triggers:
    # This should point to the location of the triggers.json configuration file
    file: ./triggers.json

```
triggers.json:

```
{
  "$schema": "https://raw.githubusercontent.com/danecreekphotography/node-deepstackai-trigger/main/src/schemas/triggerConfiguration.schema.json",
  "triggers": [
    {
      "name": "Garage",
      "watchPattern": "/images/GarageSD*.jpg",
      "enabled": true,
      "threshold": {
        "minimum": 10,
        "maximum": 100
      },
      "handlers": {
        "webRequest": {
          "triggerUris": ["http://192.168.4.100:81/admin?trigger&camera=GarageHD&user=user&pw=password"]
        },
        "mqtt": {
          "topic": "aimotion/triggers/cat"
        },
        "telegram": {
          "chatIds": [ID1111],
          "annotateImage": true
        }
      },
      "watchObjects": ["car", "truck", "person"]
    }
  ]
}
```
