### ISSUE TITLE
Creating deepstackai-blueiris_trigger_1 ... error 

### ISSUE THREAD

**Issue by Amishman** [danecreekphotography/node-deepstackai-trigger#294]
**What trouble are you having?**

I have not used Docker before but I think I have everything installed correctly. I receive an error when it is trying to "Creating deepstackai-blueiris_trigger_1". I am running Windows 10. The image folder is located in O:\AiInput.

![image](https://user-images.githubusercontent.com/5334426/85405059-d92d4580-b52d-11ea-91ff-04af328207a1.png)

This is my **docker-compose.yml**
```
version: "3.8"
services:
  trigger:
    volumes:
      # Change ./path_to_local_ai_images_folder to point to the folder that
      # will have the images to analyze
      - O:/AiInput:AiInput

    environment:
      # Change this to match the timezone the images are produced in,
      # Typically this will be the timezone of the machine running
      # the Docker container. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=America/New_York

    ports:
      # This port is used by the local web server when annotated images are enabled.
      # If you change the port used by the local web server in the settings.json file
      # this also has to change to match.
      - 4242:4242

    # ------------------------------------------------------------------------
    # Don't change anything below this line unless you know what you are doing
    secrets:
      - triggers
      - settings
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

volumes:
  localstorage:

secrets:
  settings:
    # This should point to the location of the settings.json configuration file
    file: ./settings.json
  triggers:
    # This should point to the location of the triggers.json configuration file
    file: ./triggers.json
```

This is my **triggers.json**
![image](https://user-images.githubusercontent.com/5334426/85406513-eea36f00-b52f-11ea-8828-5a8ba3073b2c.png)
![image](https://user-images.githubusercontent.com/5334426/85406600-0975e380-b530-11ea-8fa3-118d6e3b0300.png)

**Have you tried with the sample files?**

- Yes

**Have you tried the steps in the troubleshooting guide?**

https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Troubleshooting

- Yes

**Log entries**

Please copy and paste all the log messages from the Docker output

**Installation details**

 - OS:  Windows 10
 - Docker setup [e.g. sample docker-compose.yaml, Portainer, UnRAID, etc]

**Additional context**
