### ISSUE TITLE
aiinput folder in a linux mnt

### ISSUE THREAD

**Issue by Kosh42** [danecreekphotography/node-deepstackai-trigger#366]
**What trouble are you having?**

I have a Windows PC with Docker running in a WSL 2 Ubuntu install, so that I can use 'image: deepquestai/deepstack:gpu' option to use processing on CUDA cores. However, the folder holding files to analyse (c:\aiinut\ on Windows 10 root) never seems to get watched. I can see file in there when I `ls` from the command line of the mount point:
```tim@WinServer:/mnt/c/aiinput$ ls
frontsd.20200815_131629215.jpg  frontsd.20200815_131634256.jpg
```

**Have you tried with the sample files?**

- Yes

**Have you tried the steps in the troubleshooting guide?**

https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Troubleshooting

- Yes

**Log entries**

```
tim@WinServer:~/aitool2$ docker-compose up
Starting aitool2_deepstack-ai_1 ... done
Starting aitool2_trigger_1      ... done
Attaching to aitool2_deepstack-ai_1, aitool2_trigger_1
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
trigger_1       | 2020-08-15T13:23:43+01:00 [Main] ****************************************
trigger_1       | 2020-08-15T13:23:43+01:00 [Main] Starting up version 5.3.0
trigger_1       | 2020-08-15T13:23:43+01:00 [Main] Timezone offset is -60
trigger_1       | 2020-08-15T13:23:43+01:00 [Main] Current time is Sat Aug 15 2020 13:23:43 GMT+0100 (British Summer Time)
trigger_1       | 2020-08-15T13:23:43+01:00 [Settings] Loaded settings from /run/secrets/settings
trigger_1       | 2020-08-15T13:23:44+01:00 [MQTT] Connected to MQTT server mqtt://192.168.0.42:1883
trigger_1       | 2020-08-15T13:23:44+01:00 [Local storage] Creating local storage folders in /node-deepstackai-trigger.
trigger_1       | 2020-08-15T13:23:44+01:00 [Local storage] Enabling background purge every 60 minutes for files older than 30 minutes.
trigger_1       | 2020-08-15T13:23:44+01:00 [Local storage] Running purge
trigger_1       | 2020-08-15T13:23:44+01:00 [Triggers] Loaded configuration from /run/secrets/triggers
trigger_1       | 2020-08-15T13:23:44+01:00 [Triggers] Loaded configuration for Cat detector
trigger_1       | 2020-08-15T13:23:44+01:00 [Triggers] Loaded configuration for Dog detector
trigger_1       | 2020-08-15T13:23:44+01:00 [Triggers] Loaded configuration for front detector
trigger_1       | 2020-08-15T13:23:44+01:00 [Trigger manager] There are 20 images waiting in /aiinput for Cat detector.
trigger_1       | 2020-08-15T13:23:44+01:00 [Trigger manager] There are 20 images waiting in /aiinput for Dog detector.
trigger_1       | 2020-08-15T13:23:44+01:00 [Trigger manager] There are 20 images waiting in /aiinput for front detector.
trigger_1       | 2020-08-15T13:23:44+01:00 [Pushbullet] Pushbullet is disabled via settings.
trigger_1       | 2020-08-15T13:23:44+01:00 [Pushover] Pushover is disabled via settings.
trigger_1       | 2020-08-15T13:23:44+01:00 [Telegram] Telegram is disabled via settings.
trigger_1       | 2020-08-15T13:23:44+01:00 [Mqtt router] Subscribing to node-deepstackai-trigger/statistics/reset.
trigger_1       | 2020-08-15T13:23:44+01:00 [Local storage] Purge complete
trigger_1       | 2020-08-15T13:23:44+01:00 [Mqtt router] Subscribing to node-deepstackai-trigger/statistics/trigger/reset.
trigger_1       | 2020-08-15T13:23:44+01:00 [Mqtt router] Subscribing to node-deepstackai-trigger/motion.
trigger_1       | 2020-08-15T13:23:44+01:00 [Trigger front detector] Listening for new images in /aiinput/front*.jpg
trigger_1       | 2020-08-15T13:23:44+01:00 [Main] Watching for changes to /run/secrets/settings
trigger_1       | 2020-08-15T13:23:44+01:00 [Main] Watching for changes to /run/secrets/triggers
trigger_1       | 2020-08-15T13:23:44+01:00 [Main] ****************************************
trigger_1       | 2020-08-15T13:23:44+01:00 [Main] Up and running!
```

**Installation details**

 - OS: Windows 10 with WSL 2 Ununtu 20-04 LTS
 - Docker setup:

```
version: "3.8"
services:
  trigger:
    volumes:
      # Change d:/myfolder/myimages to point to the folder that will have the images
      # to analyze. Only change the local path that is before the :/aiinput portion.
      # Don't change the :/aiinput part. For example, if you are on Windows and your
      # images are stored locally in d:/blueiris/capturedImages your final line should
      # look like this:
      # d:/blueIris/capturedImages:/aiinput
      - /mnt/c/:/aiinput

    environment:
      # Change this to match the timezone the images are produced in,
      # Typically this will be the timezone of the machine running
      # the Docker container. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=Europe/London

    ports:
      # This port is used by the local web server when annotated images are enabled.
      # If you change the port used by the local web server in the settings.json file
      # this also has to change to match.
      - 4242:4242

    # ------------------------------------------------------------------------
    # Don't change anything below this line unless you know what you are doing
    secrets:
      - triggers
      - settings
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:gpu
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True
    # gpus:
    #   - all

volumes:
  localstorage:

secrets:
  settings:
    # This should point to the location of the settings.json configuration file
    file: ./settings.json
  triggers:
    # This should point to the location of the triggers.json configuration file
    file: ./triggers.json

```

**Additional context**

The log for the `aitool2_trigger_1` always shows `trigger_1       | 2020-08-15T13:23:44+01:00 [Main] Up and running!`, and never analysing when a new file (in the format front*.jpg) appears in the mounted folder.

Any guidance gratefully received.

**Comment by Kosh42** [comment]
Is this per chance related to #362

**Comment by Kosh42** [comment]
I am a numpty. Corrected this:

```
version: "3.8"
services:
  trigger:
    volumes:
      # Change d:/myfolder/myimages to point to the folder that will have the images
      # to analyze. Only change the local path that is before the :/aiinput portion.
      # Don't change the :/aiinput part. For example, if you are on Windows and your
      # images are stored locally in d:/blueiris/capturedImages your final line should
      # look like this:
      # d:/blueIris/capturedImages:/aiinput
      - /mnt/c/**aiinput**:/aiinput
```
